version: '3.7'

services:
  pg15:
    image: postgres:15.6-alpine
    restart: on-failure
    mem_limit: 256M
    environment:
      POSTGRES_PASSWORD: test22
      POSTGRES_USER: test22
      POSTGRES_DB: test22
    # Expose as 127.0.0.1:5432 on host machine for the developers
    ports:
      - '5432:5432'
    volumes:
      - .data/pg15:/var/lib/postgresql/data
      - .logs/pg15:/var/logs
      - .tmp/pg15:/tmp
      - type: bind
        source: .history/pg/.bash_history
        target: /root/.bash_history
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test22" ]
      interval: 10s
      timeout: 5s
      retries: 5

  s2d3:
    image: usalko/s2d3:0.1.8
    restart: on-failure
    mem_limit: 62M
    env_file:
      - .env
    ports:
      - 3333:3333
    volumes:
      - .data/s2d3:/tmp
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3333/" ]
      interval: 3s
      timeout: 5s
      retries: 5

  test22:
    build:
      context: .
      dockerfile: ./Dockerfile
      # extra_hosts:
      #   nexus.bia-tech.ru: 10.210.90.10
    restart: on-failure
    mem_limit: 256M
    env_file:
      - .env
    volumes:
      - '.:/home/web/app'
      - .logs/public-api:/var/log
      - type: bind
        source: .history/test22/.bash_history
        target: /home/web/.bash_history
    ports:
      - '8022:8022'
    depends_on:
      pg15:
        condition: service_healthy
      s2d3:
        condition: service_healthy
    command: >
      python3 -m uvicorn main:app --port 8022

  nginx:
    image: nginx:1.27.0-alpine
    mem_limit: 64M
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    restart: always
